name: the/libd4
version: 0.2.0
description: A library specifically designed for The programming language.
license: MIT

scripts:
  check-total-coverage: the run scripts/check-total-coverage

packages:
  the/html: 0.1.0
