name: Test Coverage

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  cancel-in-progress: true
  group: test-coverage-${{ github.event.pull_request.number || github.sha }}

jobs:
  test-coverage:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: thelang-io/setup-the@v1
      - uses: actions/cache@v4
        with:
          path: |
            coverage/openssl
            coverage/openssl-prefix
            coverage/openssl-src
          key: coverage-cmake-openssl-ubuntu-22.04-${{ hashFiles('cmake/DownloadOpenSSL.cmake') }}
      - if: runner.os == 'Windows'
        run: New-Item -ItemType Directory -Force -Path coverage
      - if: runner.os != 'Windows'
        run: mkdir -p coverage
      - run: cmake . -B ./coverage -DLIBTHE_BUILD_TESTS=ON -DLIBTHE_COVERAGE=ON
      - run: cmake --build coverage --config Debug
      - run: ctest --output-on-failure --test-dir coverage
      - run: lcov --capture -d coverage -o coverage/test.info --exclude 'test/*'
      - run: genhtml -o coverage/html coverage/test.info
      - run: the install
      - run: the script check-total-coverage
