on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Build and Test
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: macos-12
          - os: macos-13
          - os: macos-14
          - os: ubuntu-20.04
          - os: ubuntu-22.04
          - os: windows-2022
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p build
      - run: cmake . -B ./build -D CMAKE_BUILD_TYPE=Debug -D LIBTHE_BUILD_EXAMPLES=ON -D LIBTHE_BUILD_TESTS=ON
      - run: cmake --build build
      - run: cmake --install build
