name: Test Workflow

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  cancel-in-progress: true
  group: test-${{ github.event.pull_request.number || github.sha }}

jobs:
  test:
    name: Build and Test
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: macos-12
          - os: macos-13
          - os: macos-14
            install-prefix: sudo
          - os: ubuntu-20.04
            install-prefix: sudo
          - os: ubuntu-22.04
            install-prefix: sudo
          - os: windows-2022
    steps:
      - uses: actions/checkout@v4
      - if: runner.os == 'Linux'
        run: sudo apt-get install ninja-build valgrind
      - if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
      - if: runner.os == 'Windows'
        uses: ilammy/setup-nasm@v1
      - uses: actions/cache@v4
        with:
          path: [build/openssl, build/openssl-prefix, build/openssl-src]
          key: cmake-openssl-${{ hashFiles('cmake/openssl.cmake') }}
      - run: mkdir -p build
      - run: cmake . -B ./build -DCMAKE_BUILD_TYPE=Debug -DLIBTHE_BUILD_EXAMPLES=ON -DLIBTHE_BUILD_TESTS=ON
      - run: cmake --build build
      - run: ${{ matrix.config['install-prefix'] }} cmake --install build
      - if: runner.os == 'Linux'
        run: scripts/docker-entrypoint.sh
      - if: runner.os != 'Linux'
        run: ctest --output-on-failure --test-dir build
