on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Build and Test
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: macos-12
          - os: macos-13
          - os: macos-14
            install-prefix: sudo
          - os: ubuntu-20.04
            install-prefix: sudo
          - os: ubuntu-22.04
            install-prefix: sudo
          - os: windows-2022
    steps:
      - uses: actions/checkout@v4
      - if: runner.os == 'Linux'
        run: sudo apt-get install ninja-build valgrind
      - if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
      - if: runner.os == 'Windows'
        uses: ilammy/setup-nasm@v1
      - run: mkdir -p build
      - run: cmake . -B ./build -D CMAKE_BUILD_TYPE=Debug -D LIBTHE_BUILD_EXAMPLES=ON -D LIBTHE_BUILD_TESTS=ON
      - run: cmake --build build
      - run: ${{ matrix.config['install-prefix'] }} cmake --install build
      - if: runner.os == 'Linux'
        run: scripts/docker-entrypoint.sh
      - if: runner.os != 'Linux'
        run: ctest --output-on-failure --test-dir build
