on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Build and Test
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: macos-12
          - os: macos-13
          - os: macos-14
          - os: ubuntu-20.04
          - os: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - if: runner.os == 'macos'
        run: |
          brew install docker
          colima start
      - run: echo "DOCKER_TAG=${GITHUB_REF#refs/heads/}:$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
      - run: docker build -t $DOCKER_TAG .
      - run: docker run $DOCKER_TAG
